### PR TITLE
Added a VCF to_s method

### PR DESCRIPTION
**Pull request by ethering**

### CODE REVIEW

**Comment by ethering** [comment]
The addition of the tutorial into the README is in response to comments made by reviewers of the bio-samtools 2 paper

**Comment by homonecloco** [comment]
Hi, I tried to merge this change, but I don't seem to be able to push it back Ethering, could you please checkout the latest version in github. The unit tests are the only file that is having issues to get merged automatically, so please make sure you have the latest version (I also added some tests, so that may be the cause). 
Thanks, 
Ricardo.

**Comment by ethering** [comment]
Hopefully, this should work.

**Comment by homonecloco** [comment]
Thanks. I'll update the gem once I get the tests running again in TravisCI.

**Pull request merged**
