### PR TITLE
support for samtools on windows

### PR DESCRIPTION
**Pull request by moskyt**
use the BOW port of samtools on windows platforms.

### CODE REVIEW

**Comment by danmaclean** [comment]
This is a really cool patch! Thanks @moskyt.

Any idea why it's failing Travis?

**Comment by homonecloco** [comment]
Yes, it is failing because one of the dependencies is not supported by Ruby 2.0.0. I want to test this on a windows machine (not supported by travis) before merging it. I will also remove the tests for ruby 2.0.0, as it is just over a year since it is not supported anymore.

**Comment by danmaclean** [comment]
@homonecloco Great stuff, thanks!

**Comment by moskyt** [comment]
It's failing because nokogiri 1.7 is not supported with ruby 2.0. 
On the other hand, nokogiri 1.6 does not install easily on mingw.

I am not happy that I have to port my software to windows, but that's just the case.

**Pull request merged**
